package hibernatedata;
// Generated Jan 6, 2017 4:31:43 PM by Hibernate Tools 4.3.1

import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * Bookings generated by hbm2java
 */
public class Bookings implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer bookingid;
    private String companyname;
    private String customer;
    private String origin;
    private String destination;
    private double price;
    private String date;
    private String time;

    public Bookings() {
    }

    public Bookings(String companyname, String customer, String origin, String destination, double price, 
            String date, String time) {
        this.companyname = companyname;
        this.customer = customer;
        this.origin = origin;
        this.destination = destination;
        this.price = price;
        this.date = date;
        this.time = time;
    }

    public Integer getBookingid() {
        return this.bookingid;
    }

    public void setBookingid(Integer bookingid) {
        this.bookingid = bookingid;
    }

    public String getCompanyname() {
        return this.companyname;
    }

    public void setCompanyname(String companyname) {
        this.companyname = companyname;
    }

    public String getCustomer() {
        return this.customer;
    }

    public void setCustomer(String customer) {
        this.customer = customer;
    }

    public String getOrigin() {
        return this.origin;
    }

    public void setOrigin(String origin) {
        this.origin = origin;
    }

    public String getDestination() {
        return this.destination;
    }

    public void setDestination(String destination) {
        this.destination = destination;
    }

    public double getPrice() {
        return this.price;
    }

    public void setPrice(double price) {
        this.price = price;
    }
    
    public String getDate() {
        return this.date;
    }

    public void setDate(String date) {
        this.date = date;
    }
    
    public String getTime() {
        return this.time;
    }

    public void setTime(String time) {
        this.time = time;
    }

}
