package hibernatedata;
// Generated Jan 6, 2017 4:31:43 PM by Hibernate Tools 4.3.1



/**
 * Taxiinfo generated by hbm2java
 */
public class Taxiinfo  implements java.io.Serializable {


     private String username;
     private String password;
     private String email;
     private String phone;

    public Taxiinfo() {
    }

    public Taxiinfo(String username, String password, String email, String phone) {
       this.username = username;
       this.password = password;
       this.email = email;
       this.phone = phone;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }




}


