package taxigo;
// Generated Jan 3, 2017 1:02:01 PM by Hibernate Tools 4.3.1



/**
 * Admininfo generated by hbm2java
 */
public class Admininfo  implements java.io.Serializable {


     private String username;
     private String password;
     private String email;
     private String phone;

    public Admininfo() {
    }

	
    public Admininfo(String username, String password, String email) {
        this.username = username;
        this.password = password;
        this.email = email;
    }
    public Admininfo(String username, String password, String email, String phone) {
       this.username = username;
       this.password = password;
       this.email = email;
       this.phone = phone;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }




}


