package taxigo;
// Generated Jan 3, 2017 1:02:01 PM by Hibernate Tools 4.3.1



/**
 * Bookings generated by hbm2java
 */
public class Bookings  implements java.io.Serializable {


     private Integer bookingid;
     private Clientinfo clientinfo;
     private Taxiinfo taxiinfo;
     private String origin;
     private String destination;
     private double price;

    public Bookings() {
    }

    public Bookings(Clientinfo clientinfo, Taxiinfo taxiinfo, String origin, String destination, double price) {
       this.clientinfo = clientinfo;
       this.taxiinfo = taxiinfo;
       this.origin = origin;
       this.destination = destination;
       this.price = price;
    }
   
    public Integer getBookingid() {
        return this.bookingid;
    }
    
    public void setBookingid(Integer bookingid) {
        this.bookingid = bookingid;
    }
    public Clientinfo getClientinfo() {
        return this.clientinfo;
    }
    
    public void setClientinfo(Clientinfo clientinfo) {
        this.clientinfo = clientinfo;
    }
    public Taxiinfo getTaxiinfo() {
        return this.taxiinfo;
    }
    
    public void setTaxiinfo(Taxiinfo taxiinfo) {
        this.taxiinfo = taxiinfo;
    }
    public String getOrigin() {
        return this.origin;
    }
    
    public void setOrigin(String origin) {
        this.origin = origin;
    }
    public String getDestination() {
        return this.destination;
    }
    
    public void setDestination(String destination) {
        this.destination = destination;
    }
    public double getPrice() {
        return this.price;
    }
    
    public void setPrice(double price) {
        this.price = price;
    }




}


