package taxigo;
// Generated Jan 3, 2017 1:02:01 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Clientinfo generated by hbm2java
 */
public class Clientinfo  implements java.io.Serializable {


     private String username;
     private String password;
     private String email;
     private String phone;
     private boolean reported;
     private Set bookingses = new HashSet(0);

    public Clientinfo() {
    }

	
    public Clientinfo(String username, String password, String email, boolean reported) {
        this.username = username;
        this.password = password;
        this.email = email;
        this.reported = reported;
    }
    public Clientinfo(String username, String password, String email, String phone, boolean reported, Set bookingses) {
       this.username = username;
       this.password = password;
       this.email = email;
       this.phone = phone;
       this.reported = reported;
       this.bookingses = bookingses;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public boolean isReported() {
        return this.reported;
    }
    
    public void setReported(boolean reported) {
        this.reported = reported;
    }
    public Set getBookingses() {
        return this.bookingses;
    }
    
    public void setBookingses(Set bookingses) {
        this.bookingses = bookingses;
    }




}


