package taxigo;
// Generated Jan 3, 2017 1:02:01 PM by Hibernate Tools 4.3.1



/**
 * Taxioperator generated by hbm2java
 */
public class Taxioperator  implements java.io.Serializable {


     private String operator;
     private Taxiinfo taxiinfo;
     private double baserate;
     private double priceperkm;
     private Double weekendfee;
     private int rating;

    public Taxioperator() {
    }

	
    public Taxioperator(Taxiinfo taxiinfo, double baserate, double priceperkm, int rating) {
        this.taxiinfo = taxiinfo;
        this.baserate = baserate;
        this.priceperkm = priceperkm;
        this.rating = rating;
    }
    public Taxioperator(Taxiinfo taxiinfo, double baserate, double priceperkm, Double weekendfee, int rating) {
       this.taxiinfo = taxiinfo;
       this.baserate = baserate;
       this.priceperkm = priceperkm;
       this.weekendfee = weekendfee;
       this.rating = rating;
    }
   
    public String getOperator() {
        return this.operator;
    }
    
    public void setOperator(String operator) {
        this.operator = operator;
    }
    public Taxiinfo getTaxiinfo() {
        return this.taxiinfo;
    }
    
    public void setTaxiinfo(Taxiinfo taxiinfo) {
        this.taxiinfo = taxiinfo;
    }
    public double getBaserate() {
        return this.baserate;
    }
    
    public void setBaserate(double baserate) {
        this.baserate = baserate;
    }
    public double getPriceperkm() {
        return this.priceperkm;
    }
    
    public void setPriceperkm(double priceperkm) {
        this.priceperkm = priceperkm;
    }
    public Double getWeekendfee() {
        return this.weekendfee;
    }
    
    public void setWeekendfee(Double weekendfee) {
        this.weekendfee = weekendfee;
    }
    public int getRating() {
        return this.rating;
    }
    
    public void setRating(int rating) {
        this.rating = rating;
    }




}


